### ISSUE TITLE
New idea for this mod

### ISSUE THREAD

**Issue by Quackdd** [Kabaril/sane-randomizer#1]
Hi! I would like to do a fun thing with my friends and maybe for YouTube where we did a 1v1 race in terraria using the weapon damage randomizer. I was looking to have something so that the spread of damage increase (1% to 1000%) favors 100% and has the same, much lower chance of it reaching 1% damage and 1000% damage. It would have half the spread of chance lowering the damage and the other half making it higher. This would be a feature where you could have a separate option to activate this. I was looking to do something like Mars and his friends did since it looked fun. This was a great project otherwise and I noticed no bugs when messing around with it, so keep up the good work. Please respond with what you may do with this when you see it. Thanks.

**Comment by Kabaril** [comment]
I added a option that should do that called "Favor Center Random Values".
The setting ranges from -100 (favor less normal values) to 100 (favor normal values)

**Comment by Quackdd** [comment]
> I added a option that should do that called "Favor Center Random Values". The setting ranges from -100 (favor less normal values) to 100 (favor normal values)

Very cool! Thank you!
